AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6.6
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 21

Metrics/BlockLength:
  ExcludedMethods: ['describe']

Naming/FileName:
  Enabled: false